### ISSUE TITLE
使用NWPUV2数据集训练和测试

### ISSUE THREAD

**Issue by hui-yiming** [RSer-XDU/G-FSDet#13]
运行 test.py文件测试时出现错误：
load checkpoint from local path: work_dirs_NW/ETF_r101_fpn_nwpuv2-split1_10shot-fine-tuning/latest.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 293/293, 21.0 task/s, elapsed: 14s, ETA:     0s
---------------iou_thr: 0.5---------------
Traceback (most recent call last):
  File "./tools/detection/test.py", line 226, in <module>
    main()
  File "./tools/detection/test.py", line 222, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/root/autodl-tmp/G-FSDet/mmfewshot/detection/datasets/nwpuv2.py", line 418, in evaluate
    use_legacy_coordinate=True)
  File "/root/autodl-tmp/G-FSDet/mmfewshot/detection/core/evaluation/mean_ap.py", line 153, in eval_map
    mean_ap, eval_results, classes, area_ranges, logger=logger)
  File "/root/miniconda3/envs/G-Fsdet/lib/python3.7/site-packages/mmdet/core/evaluation/mean_ap.py", line 502, in print_map_summary
    label_names[j], num_gts[i, j], results[j]['num_dets'],
IndexError: tuple index out of range
想问一下为什么会这样呢？

**Comment by guanlaoshi** [comment]
> 

这有挺多情况的：有可能你基类训练后的模型没有进行转头操作（就是step2: reshape the bbox head of base model for few shot fine-tuning），然后第三步记得把cfg里面的模型路径改成转好头的模型

**Comment by imyjx** [comment]
求助各位大佬！！！，我跑NWPUv2数据集的BaseTraning，mAP只有20多。
配置文件是DIOR的配置文件改过来的，尝试过调整BS和学习率，目前依然是20多的精度水平。这是什么情况，有大佬了解吗？

**Comment by guanlaoshi** [comment]
> 求助各位大佬！！！，我跑NWPUv2数据集的BaseTraning，mAP只有20多。 配置文件是DIOR的配置文件改过来的，尝试过调整BS和学习率，目前依然是20多的精度水平。这是什么情况，有大佬了解吗？

不会啊，我训练出来90.66%，你对比一下我的cfg文件呢：
![image](https://github.com/RSer-XDU/G-FSDet/assets/86900732/342e91f4-64ca-4512-996a-eb0a7a96b3ce)

**Comment by imyjx** [comment]
> > 求助各位大佬！！！，我跑NWPUv2数据集的BaseTraning，mAP只有20多。 配置文件是DIOR的配置文件改过来的，尝试过调整BS和学习率，目前依然是20多的精度水平。这是什么情况，有大佬了解吗？
> 
> 不会啊，我训练出来90.66%，你对比一下我的cfg文件呢： ![image](https://user-images.githubusercontent.com/86900732/264279212-342e91f4-64ca-4512-996a-eb0a7a96b3ce.png)
感谢大佬光速回复！！！
我检查了配置文件，没有问题。
我发现问题是在读取数据的时候，没有把7个基类的训练数据都读取到。
![image](https://github.com/RSer-XDU/G-FSDet/assets/26484929/224c3af9-cd05-45bf-a879-9aaa82e77cf9)
但是使用的nwpuv2数据集，和mmfewshot/detection/datasets/nwpuv2.py我都没有修改过，这会是什么问题呢？

**Comment by guanlaoshi** [comment]
> > > 求助各位大佬！！！，我跑NWPUv2数据集的BaseTraning，mAP只有20多。 配置文件是DIOR的配置文件改过来的，尝试过调整BS和学习率，目前依然是20多的精度水平。这是什么情况，有大佬了解吗？
> > 
> > 
> > 不会啊，我训练出来90.66%，你对比一下我的cfg文件呢： ![image](https://user-images.githubusercontent.com/86900732/264279212-342e91f4-64ca-4512-996a-eb0a7a96b3ce.png)
> > 感谢大佬光速回复！！！
> > 我检查了配置文件，没有问题。
> > 我发现问题是在读取数据的时候，没有把7个基类的训练数据都读取到。
> > ![image](https://user-images.githubusercontent.com/26484929/264302644-224c3af9-cd05-45bf-a879-9aaa82e77cf9.png)
> > 但是使用的nwpuv2数据集，和mmfewshot/detection/datasets/nwpuv2.py我都没有修改过，这会是什么问题呢？

我感觉你数据集好像有点问题，
![image](https://github.com/RSer-XDU/G-FSDet/assets/86900732/cea89541-e480-45a1-b6ac-d85643974020)
这个显示的确是不全的，但不影响结果。但是你的每一类的数量不对，感觉是数据集的问题。你使用的是这个吗？https://drive.google.com/file/d/1ufoSMK_J0cHth-Or5bEmbAIaH8SxzsXo/view?usp=sharing

**Comment by imyjx** [comment]
![image](https://github.com/RSer-XDU/G-FSDet/assets/26484929/b172c22c-0b12-425f-833d-8f87d062ebdb)
我又重新下载了一遍然后。。。。 出现了这个问题，路径什么的都排查过了，但是一直报错。。。

**Comment by imyjx** [comment]
> > > > 求助各位大佬！！！，我跑NWPUv2数据集的BaseTraning，mAP只有20多。 配置文件是DIOR的配置文件改过来的，尝试过调整BS和学习率，目前依然是20多的精度水平。这是什么情况，有大佬了解吗？
> > > 
> > > 
> > > 不会啊，我训练出来90.66%，你对比一下我的cfg文件呢： ![image](https://user-images.githubusercontent.com/86900732/264279212-342e91f4-64ca-4512-996a-eb0a7a96b3ce.png)
> > > 感谢大佬光速回复！！！
> > > 我检查了配置文件，没有问题。
> > > 我发现问题是在读取数据的时候，没有把7个基类的训练数据都读取到。
> > > ![image](https://user-images.githubusercontent.com/26484929/264302644-224c3af9-cd05-45bf-a879-9aaa82e77cf9.png)
> > > 但是使用的nwpuv2数据集，和mmfewshot/detection/datasets/nwpuv2.py我都没有修改过，这会是什么问题呢？
> 
> 我感觉你数据集好像有点问题， ![image](https://user-images.githubusercontent.com/86900732/264305304-cea89541-e480-45a1-b6ac-d85643974020.png) 这个显示的确是不全的，但不影响结果。但是你的每一类的数量不对，感觉是数据集的问题。你使用的是这个吗？https://drive.google.com/file/d/1ufoSMK_J0cHth-Or5bEmbAIaH8SxzsXo/view?usp=sharing

![image](https://github.com/RSer-XDU/G-FSDet/assets/26484929/f54ebe10-12ce-4754-9b2b-cae7e6200e3f)
大佬，我用的应该是，但是为了确认我又重新下载了一边，然后再跑就路径不对了。。。 但是路径什么的我都没改过。。。

**Comment by imyjx** [comment]
数据集不知道什么时间损坏了（愚蠢的我 -_-。 ），感谢大佬！！！

**Comment by hui-yiming** [comment]
![34e15142ef7e588cd72feae191a83159](https://github.com/RSer-XDU/G-FSDet/assets/131271448/d3a27a45-bddb-487d-bf10-00bd1d2635fd)
大佬们，请问我训练dior数据集的时候没有出现这种现象，但是训练nwpuv2的base training为什么会出现这种现象呢？能帮忙给我看一下吗

**Comment by guanlaoshi** [comment]
> ![34e15142ef7e588cd72feae191a83159](https://private-user-images.githubusercontent.com/131271448/292695760-d3a27a45-bddb-487d-bf10-00bd1d2635fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0Njc0NDIsIm5iZiI6MTcwMzQ2NzE0MiwicGF0aCI6Ii8xMzEyNzE0NDgvMjkyNjk1NzYwLWQzYTI3YTQ1LWJkZGItNDg3ZC1iZjEwLTAwYmQxZDI2MzVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMTE5MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjJlZTAxY2Q4YzMyOTg4YTI5NmMxYjQwMWYzMzViZTMwOTdkNTdkYmUyM2ZmMGNkMDk5OWMwOTNiOTQ4OTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q9glvL0P5cS7G426BKd49j-Kn46tUHhPvGcbSvAE-1Y) 大佬们，请问我训练dior数据集的时候没有出现这种现象，但是训练nwpuv2的base training为什么会出现这种现象呢？能帮忙给我看一下吗

感觉像是训练类多了，可以核对一下这两个文件configs/detection/ETF/nwpuv2/split1/tfa_r101_fpn_nwpuv2_split1_base-training.py和mmfewshot/detection/datasets/nwpuv2.py
![image](https://github.com/RSer-XDU/G-FSDet/assets/86900732/58af8aa2-cbb3-4753-9465-8ccf3f4cea5b)
![image](https://github.com/RSer-XDU/G-FSDet/assets/86900732/88f64ef2-ccb7-480c-9e87-1e41f6d59427)

**Comment by hui-yiming** [comment]
但是我看起来好像跟您这个是一样的
![555b578a4280c7c6724b554a1c7cb71f](https://github.com/RSer-XDU/G-FSDet/assets/131271448/673a34ad-bfad-49ae-a6a1-eacc1395b837)
![b07fe6ef12345d165f02a54a33ed6ba3](https://github.com/RSer-XDU/G-FSDet/assets/131271448/896fbd7f-be01-421d-b77d-0d39a4317557)

**Comment by hui-yiming** [comment]
是否是因为我看到nwpuv的train应该是879，这里只有560张呢？
![Uploading 截屏2023-12-25 09.51.17.png…]()

**Comment by hui-yiming** [comment]
是否是因为我看到nwpuv的train应该是879，这里只有560张呢？

**Comment by guanlaoshi** [comment]
> 但是我看起来好像跟您这个是一样的 ![555b578a4280c7c6724b554a1c7cb71f](https://private-user-images.githubusercontent.com/131271448/292697615-673a34ad-bfad-49ae-a6a1-eacc1395b837.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NjkzNDQsIm5iZiI6MTcwMzQ2OTA0NCwicGF0aCI6Ii8xMzEyNzE0NDgvMjkyNjk3NjE1LTY3M2EzNGFkLWJmYWQtNDlhZS1hNmExLWVhY2MxMzk1YjgzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMTUwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGFkY2Y0Njg2MzNmMjgwN2M4YzQyMzhmZmVkMDI1ZGZjOTcyNGVjM2ZlZmFlNmI4MGVjNGMxMjE3MzQxYjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8jAn-M0YvYTbYLg55vzKjl7-s06D3xneJCbgyPrzGCk) ![b07fe6ef12345d165f02a54a33ed6ba3](https://private-user-images.githubusercontent.com/131271448/292697618-896fbd7f-be01-421d-b77d-0d39a4317557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NjkzNDQsIm5iZiI6MTcwMzQ2OTA0NCwicGF0aCI6Ii8xMzEyNzE0NDgvMjkyNjk3NjE4LTg5NmZiZDdmLWJlMDEtNDIxZC1iNzdkLTBkMzlhNDMxNzU1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMTUwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGU5OTgwYTQ3NGY2MDZjZGMzMWMwNTk3MWNjYzAzMDM5NGU0OTBjNmQ5MTZkZjM1YWRlMzlmMmM2MzVjYjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vMsVHjCf-qMA3ffo8pNY762BLEweTgxEvufUkLUcMaI)

![image](https://github.com/RSer-XDU/G-FSDet/assets/86900732/31dedfd1-3cad-4d04-bd00-80200076a7d2)
基类训练的时候 最后的头是7个，是通过initialize_bbox_head.py，变成10个的

**Comment by hui-yiming** [comment]
是这样的！太感谢您啦！

**Comment by hui-yiming** [comment]
太感谢您了！是不是在微调的时候，initialize_bbox_head.py，中，参数VOC_TAR_SIZE = 20在根据数据集进行类别改变就可以了？
<img width="708" alt="截屏2023-12-25 10 07 53" src="https://github.com/RSer-XDU/G-FSDet/assets/131271448/fb6bf362-380e-49d9-bf0b-ee2cafbe2567">

**Comment by guanlaoshi** [comment]
> 太感谢您了！是不是在微调的时候，initialize_bbox_head.py，中，参数VOC_TAR_SIZE = 20在根据数据集进行类别改变就可以了？ <img alt="截屏2023-12-25 10 07 53" width="708" src="https://private-user-images.githubusercontent.com/131271448/292699035-fb6bf362-380e-49d9-bf0b-ee2cafbe2567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzA2NTMsIm5iZiI6MTcwMzQ3MDM1MywicGF0aCI6Ii8xMzEyNzE0NDgvMjkyNjk5MDM1LWZiNmJmMzYyLTM4MGUtNDlkOS1iZjBiLWVlMmNhZmJlMjU2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjEyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTQwMDRlNjFiZmJjMzNiOGE5NDNhYmNiMGRmOTNmY2M1ZTI0M2JmMTUzM2YxZGY0ZDJhOWMxZmE5ODkyMzY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UyKP4HbILYIycKwr5ig1Qf2q4ONy_Ti1yEfQnFkTf1s">

是的，TAR_SIZE代表总数量，所以如果要微调nwpuv2的话，需要在这个py文件修改一下

**Comment by qjh666888** [comment]
> > 求助各位大佬！！！，我跑NWPUv2数据集的BaseTraning，mAP只有20多。 配置文件是DIOR的配置文件改过来的，尝试过调整BS和学习率，目前依然是20多的精度水平。这是什么情况，有大佬了解吗？
> 
> 不会啊，我训练出来90.66%，你对比一下我的cfg文件呢： ![image](https://github.com/RSer-XDU/G-FSDet/assets/86900732/342e91f4-64ca-4512-996a-eb0a7a96b3ce)

大佬，请问您那有diro其他split的配置文件嘛？
