### ISSUE TITLE
Install mmcv and report an error

### ISSUE THREAD

**Issue by 75391fwh** [RSer-XDU/G-FSDet#15]
Traceback (most recent call last):
  File "/data/fwh/G-FSDet/./tools/detection/train.py", line 11, in <module>
    from mmcv import Config, DictAction
ImportError: cannot import name 'Config' from 'mmcv' (/home/fwh/anaconda3/envs/gfsdet/lib/python3.9/site-packages/mmcv/__init__.py)
Traceback (most recent call last):
  File "/data/fwh/G-FSDet/./tools/detection/train.py", line 11, in <module>
    from mmcv import Config, DictAction
ImportError: cannot import name 'Config' from 'mmcv' (/home/fwh/anaconda3/envs/gfsdet/lib/python3.9/site-packages/mmcv/__init__.py)

**Comment by RSer-XDU** [comment]
I guess it may be a problem with the mmcv version.
You can refer to https://github.com/open-mmlab/mmfewshot/blob/main/docs/en/install.md
